version: '3.9'

services:
  fastify_backend:
    container_name: fastify_backend
    image: gabrielimage/fastify_backend
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastifydb
      POSTGRES_SERVICE: postgres
      POSTGRES_PORT: 5432
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:13'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastifydb
      POSTGRES_PORT: 5432
    networks:
      - backend
    volumes:
      - fastify_volume:/var/lib/postgres/data

volumes:
  fastify_volume: {}
networks:
  backend:






